-- =============================================================================
-- Least-privilege DB access: api_app_role for legal_acceptances
-- =============================================================================
-- 
-- PURPOSE:
--   Grant INSERT + SELECT ONLY (no UPDATE/DELETE) to api_app_role on the
--   legal_acceptances table for LGPD-compliant append-only access.
--
-- WHEN TO RUN:
--   - After the LegalAcceptance migration (20260913172057_add_legal_acceptance_model)
--     has been applied to the target database.
--   - Before the API application switches to using api_app_role credentials.
--
-- IDEMPOTENT:
--   Safe to re-run multiple times. Uses IF NOT EXISTS and DO $$ blocks for
--   idempotent role/grant operations.
--
-- SECURITY POLICY:
--   - NO UPDATE: legal_acceptances is immutable after insertion
--   - NO DELETE: records removed ONLY via User CASCADE or compliance purge
--   - UPDATE/DELETE reserved for DBA/compliance role only
--
-- RELATED:
--   - PR #6: https://github.com/GabrielCampos07/origo.app/pull/6
--   - Legal V2 least-privilege follow-up
--
-- =============================================================================

-- Create api_app_role if it doesn't exist
-- Note: Password must be set separately via ALTER ROLE or environment config
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT FROM pg_catalog.pg_roles WHERE rolname = 'api_app_role'
  ) THEN
    CREATE ROLE api_app_role WITH LOGIN;
    RAISE NOTICE 'Created role: api_app_role';
  ELSE
    RAISE NOTICE 'Role api_app_role already exists';
  END IF;
END
$$;

-- Grant USAGE on schema public (required for accessing objects)
GRANT USAGE ON SCHEMA public TO api_app_role;

-- Grant SELECT + INSERT only on legal_acceptances
-- Explicitly NO UPDATE or DELETE
GRANT SELECT, INSERT ON TABLE public.legal_acceptances TO api_app_role;

-- Note: No sequence grant needed - legal_acceptances.id uses CUID (generated by app)

-- Verify grants (informational query - comment out in production automation)
-- SELECT 
--   grantee, 
--   privilege_type 
-- FROM information_schema.table_privileges 
-- WHERE table_schema = 'public' 
--   AND table_name = 'legal_acceptances'
--   AND grantee = 'api_app_role'
-- ORDER BY privilege_type;

-- Expected result:
-- grantee      | privilege_type
-- -------------|---------------
-- api_app_role | INSERT
-- api_app_role | SELECT

DO $$
BEGIN
  RAISE NOTICE 'Grants applied: api_app_role has SELECT + INSERT on legal_acceptances';
END
$$;
