-- =============================================================================
-- Least-privilege DB access: api_app_role for referral tables
-- =============================================================================
-- 
-- PURPOSE:
--   Grant INSERT + SELECT + UPDATE (referrals only) to api_app_role on the
--   referral system tables for least-privilege MVP access.
--
-- WHEN TO RUN:
--   - After the Referral MVP migration (20260913181200_add_referral_mvp_schema)
--     has been applied to the target database.
--   - Before the API application switches to using api_app_role credentials.
--
-- IDEMPOTENT:
--   Safe to re-run multiple times. Uses IF NOT EXISTS and DO $$ blocks for
--   idempotent role/grant operations.
--
-- SECURITY POLICY:
--   referral_codes:
--     - INSERT: API can create new referral codes
--     - SELECT: API can read codes for validation
--     - NO UPDATE: codes are immutable after creation
--     - NO DELETE: code removal reserved for DBA/admin only
--   
--   referrals:
--     - INSERT: API can record new referral attributions
--     - SELECT: API can read referral status and details
--     - UPDATE: API can update status (PENDING → ACTIVE → COMPLETED/CANCELLED)
--     - NO DELETE: referral records are immutable; deletion reserved for DBA
--   
--   referral_payouts:
--     - INSERT: API can append payout ledger entries
--     - SELECT: API can read payout history
--     - NO UPDATE: append-only ledger (amounts/timestamps immutable)
--     - NO DELETE: ledger entries are permanent; deletion reserved for DBA
--
-- DATA INTEGRITY ENFORCEMENT (DB Security Checklist):
--   Add CHECK constraint to prevent self-referrals (referrerUserId = referredUserId).
--   This is enforced at the database level as a hard data integrity rule.
--   
--   Verification query for DBA/audit review:
--   
--     SELECT id, "referrerUserId", "referredUserId", "createdAt"
--     FROM public.referrals
--     WHERE "referrerUserId" = "referredUserId";
--   
--   Expected result: 0 rows (constraint prevents insertion)
--
-- RELATED:
--   - Referral MVP schema commit: 4a49c9a (feat(db): referral MVP schema)
--   - Migration: apps/api/prisma/migrations/20260913181200_add_referral_mvp_schema/
--   - Documentation: docs/REFERRAL_MVP.md
--   - Pattern reference: deploy/sql/01_api_app_role_legal_acceptances.sql (PR #9)
--
-- =============================================================================

-- Create api_app_role if it doesn't exist
-- Note: Password must be set separately via ALTER ROLE or environment config
-- Note: This role may already exist from 01_api_app_role_legal_acceptances.sql
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT FROM pg_catalog.pg_roles WHERE rolname = 'api_app_role'
  ) THEN
    CREATE ROLE api_app_role WITH LOGIN;
    RAISE NOTICE 'Created role: api_app_role';
  ELSE
    RAISE NOTICE 'Role api_app_role already exists';
  END IF;
END
$$;

-- Grant USAGE on schema public (required for accessing objects)
-- Idempotent: safe to grant multiple times
GRANT USAGE ON SCHEMA public TO api_app_role;

-- ==================== referral_codes ====================
-- Grant SELECT + INSERT only on referral_codes
-- Explicitly NO UPDATE or DELETE (codes are immutable)
GRANT SELECT, INSERT ON TABLE public.referral_codes TO api_app_role;

-- Grant USAGE + SELECT on the id sequence (if using serial/sequence)
-- Note: referral_codes.id uses CUID (generated by app), no sequence grant needed

-- ==================== referrals ====================
-- Grant SELECT + INSERT + UPDATE on referrals
-- UPDATE needed for status transitions (PENDING → ACTIVE → COMPLETED/CANCELLED)
-- Explicitly NO DELETE (referral records are permanent)
GRANT SELECT, INSERT, UPDATE ON TABLE public.referrals TO api_app_role;

-- ==================== referral_payouts ====================
-- Grant SELECT + INSERT only on referral_payouts
-- Explicitly NO UPDATE or DELETE (append-only ledger)
GRANT SELECT, INSERT ON TABLE public.referral_payouts TO api_app_role;

-- Note: referral_payouts.id uses CUID (generated by app), no sequence grant needed

-- =============================================================================
-- DATA INTEGRITY: Add CHECK constraint to prevent self-referrals
-- =============================================================================

-- Add CHECK constraint to prevent referrerUserId = referredUserId
-- Idempotent: only adds if constraint doesn't already exist
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_catalog.pg_constraint
    WHERE conname = 'referrals_no_self_referral_check'
      AND conrelid = 'public.referrals'::regclass
  ) THEN
    ALTER TABLE public.referrals
    ADD CONSTRAINT referrals_no_self_referral_check
    CHECK ("referrerUserId" <> "referredUserId");
    
    RAISE NOTICE 'Added CHECK constraint: referrals_no_self_referral_check';
  ELSE
    RAISE NOTICE 'CHECK constraint referrals_no_self_referral_check already exists';
  END IF;
END
$$;

-- Verify grants (informational query - comment out in production automation)
-- SELECT 
--   table_name,
--   grantee, 
--   privilege_type 
-- FROM information_schema.table_privileges 
-- WHERE table_schema = 'public' 
--   AND table_name IN ('referral_codes', 'referrals', 'referral_payouts')
--   AND grantee = 'api_app_role'
-- ORDER BY table_name, privilege_type;

-- Expected result:
-- table_name       | grantee      | privilege_type
-- -----------------|--------------|---------------
-- referral_codes   | api_app_role | INSERT
-- referral_codes   | api_app_role | SELECT
-- referral_payouts | api_app_role | INSERT
-- referral_payouts | api_app_role | SELECT
-- referrals        | api_app_role | INSERT
-- referrals        | api_app_role | SELECT
-- referrals        | api_app_role | UPDATE

DO $$
BEGIN
  RAISE NOTICE 'Grants applied: api_app_role has appropriate privileges on referral tables';
  RAISE NOTICE '  - referral_codes: SELECT + INSERT (no UPDATE/DELETE)';
  RAISE NOTICE '  - referrals: SELECT + INSERT + UPDATE (no DELETE)';
  RAISE NOTICE '  - referral_payouts: SELECT + INSERT (no UPDATE/DELETE)';
  RAISE NOTICE 'CHECK constraint enforced: no self-referrals allowed (referrerUserId <> referredUserId)';
END
$$;
