-- =============================================================================
-- Least-privilege DB access: api_app_role for authentication tables
-- =============================================================================
-- 
-- PURPOSE:
--   Grant SELECT + UPDATE on users, SELECT + INSERT + UPDATE on token tables
--   to api_app_role for login/auth flows (prod login currently 500 because
--   only legal+referral grants exist in 01/02).
--
-- WHEN TO RUN:
--   - After P0 auth migrations have been applied to the target database.
--   - After 01_api_app_role_legal_acceptances.sql has been applied.
--   - After 02_api_app_role_referral_tables.sql has been applied.
--   - Before the API application switches to using api_app_role credentials.
--
-- IDEMPOTENT:
--   Safe to re-run multiple times. Uses IF NOT EXISTS, explicit REVOKE ALL,
--   and DO $$ blocks for idempotent role/grant operations.
--
-- SECURITY POLICY:
--   users:
--     - SELECT: API can read user profiles for authentication/authorization
--     - UPDATE: API can update lastLoginAt, password hash, profile fields
--     - NO INSERT: signup/cadastro on HOLD (elevated role required)
--     - NO DELETE: user removal reserved for DBA/compliance role only
--     - ⚠️  UPDATE is table-wide — app/Back Sec MUST NOT escalate `role` field
--         without additional row-level security policy (RLS) enforcement
--   
--   password_reset_tokens:
--     - SELECT: API can validate reset tokens
--     - INSERT: API can create new password reset requests
--     - UPDATE: API can mark tokens as used/invalidated
--     - NO DELETE: D8 purge requires elevated role (future origo_cron role)
--   
--   refresh_tokens:
--     - SELECT: API can validate refresh tokens
--     - INSERT: API can create new refresh tokens at login
--     - UPDATE: API can rotate/revoke tokens
--     - NO DELETE: D8 purge requires elevated role (future origo_cron role)
--
-- FUTURE WORK:
--   - DELETE on token tables: D8 purge requires elevated role (e.g. origo_cron)
--     with DELETE-only on tokens; keep api_app_role without DELETE. To implement,
--     create dedicated origo_cron role and run purge jobs as origo_cron.
--   - INSERT on users: When signup resumes, either grant INSERT to api_app_role
--     or create separate signup_role with INSERT-only on users.
--
-- RELATED:
--   - deploy/sql/01_api_app_role_legal_acceptances.sql (PR #9)
--   - deploy/sql/02_api_app_role_referral_tables.sql (Referral MVP)
--   - D8 Token Purge: docs/D8-TOKEN-PURGE.md
--
-- =============================================================================

-- Create api_app_role if it doesn't exist
-- Note: Password must be set separately via ALTER ROLE or environment config
-- Note: This role may already exist from 01/02 scripts
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT FROM pg_catalog.pg_roles WHERE rolname = 'api_app_role'
  ) THEN
    CREATE ROLE api_app_role WITH LOGIN;
    RAISE NOTICE 'Created role: api_app_role';
  ELSE
    RAISE NOTICE 'Role api_app_role already exists';
  END IF;
END
$$;

-- Grant USAGE on schema public (required for accessing objects)
-- Idempotent: safe to grant multiple times
GRANT USAGE ON SCHEMA public TO api_app_role;

-- ==================== users ====================
-- Explicit least privilege: REVOKE ALL first, then grant only what's needed
REVOKE ALL ON TABLE public.users FROM api_app_role;

-- Grant SELECT + UPDATE only on users
-- NO INSERT (signup on hold), NO DELETE (user removal = DBA/compliance only)
GRANT SELECT, UPDATE ON TABLE public.users TO api_app_role;

-- ⚠️  SECURITY NOTE:
-- UPDATE privilege is table-wide. Application MUST enforce business rules to
-- prevent unauthorized role escalation (e.g., student → admin). Consider RLS
-- policies or app-level authorization checks before allowing role field updates.

-- ==================== password_reset_tokens ====================
-- Explicit least privilege: REVOKE ALL first, then grant only what's needed
REVOKE ALL ON TABLE public.password_reset_tokens FROM api_app_role;

-- Grant SELECT + INSERT + UPDATE on password_reset_tokens
-- NO DELETE (D8 purge = elevated role, see FUTURE WORK above)
GRANT SELECT, INSERT, UPDATE ON TABLE public.password_reset_tokens TO api_app_role;

-- ==================== refresh_tokens ====================
-- Explicit least privilege: REVOKE ALL first, then grant only what's needed
REVOKE ALL ON TABLE public.refresh_tokens FROM api_app_role;

-- Grant SELECT + INSERT + UPDATE on refresh_tokens
-- NO DELETE (D8 purge = elevated role, see FUTURE WORK above)
GRANT SELECT, INSERT, UPDATE ON TABLE public.refresh_tokens TO api_app_role;

-- Note: Token table IDs use CUID (generated by app), no sequence grant needed

-- Verify grants (informational query - comment out in production automation)
-- SELECT 
--   table_name,
--   grantee, 
--   privilege_type 
-- FROM information_schema.table_privileges 
-- WHERE table_schema = 'public' 
--   AND table_name IN ('users', 'password_reset_tokens', 'refresh_tokens')
--   AND grantee = 'api_app_role'
-- ORDER BY table_name, privilege_type;

-- Expected result:
-- table_name              | grantee      | privilege_type
-- ------------------------|--------------|---------------
-- password_reset_tokens   | api_app_role | INSERT
-- password_reset_tokens   | api_app_role | SELECT
-- password_reset_tokens   | api_app_role | UPDATE
-- refresh_tokens          | api_app_role | INSERT
-- refresh_tokens          | api_app_role | SELECT
-- refresh_tokens          | api_app_role | UPDATE
-- users                   | api_app_role | SELECT
-- users                   | api_app_role | UPDATE

DO $$
BEGIN
  RAISE NOTICE 'Grants applied: api_app_role has appropriate privileges on auth tables';
  RAISE NOTICE '  - users: SELECT + UPDATE (no INSERT/DELETE)';
  RAISE NOTICE '  - password_reset_tokens: SELECT + INSERT + UPDATE (no DELETE)';
  RAISE NOTICE '  - refresh_tokens: SELECT + INSERT + UPDATE (no DELETE)';
  RAISE NOTICE '⚠️  SECURITY: UPDATE on users is table-wide — app must enforce role escalation checks';
END
$$;
